title: "Arundhati Vibhute Portfolio"
description: "Full Stack Developer | React | Spring Boot | AWS Certified"

baseurl: ""
url: "https://arundhatikundap.github.io"

theme: jekyll-theme-minimal

sass:
  style: compressed


linkedin_username: arundhati-vibhute-17702819
github_username: ArundhatiKundap
email: arundhatik0@gmail.com


