title: "Arundhati Vibhute Portfolio"
description: "Full Stack Developer | React | Spring Boot | AWS Certified"

baseurl: "" # keep empty for user/organization GitHub Pages
url: "https://arundhatikundap.github.io"

theme: jekyll-theme-minimal

sass:
  style: compressed

# Social links — must be only usernames, not full URLs
linkedin_username: arundhati-vibhute-17702819
github_username: ArundhatiKundap
email: arundhatik0@gmail.com


